name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - name: Setup Java environment based on AdoptOpenJDK
        uses: joschi/setup-jdk@v1
        with:
          java-version: openjdk11
          openjdk_impl: openj9
      - name: Init
        run: ./gradlew version
      - name: Compile
        run: ./gradlew classes
      - name: Test
        run: ./gradlew test
#      - name: Publish
#        run: ./gradlew artifactoryPublish -PrepoUsername=${{ secrets.REPO_USR }} -PrepoPassword=${{ secrets.REPO_PSW }}
