name: Java CI

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout with all branches and tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'

      - name: Compile
        run: ./gradlew version classes

      - name: Test
        run: ./gradlew test
