name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Java environment based on AdoptOpenJDK
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: openjdk11
          openjdk_impl: openj9
      - name: Compile
        run: ./gradlew classes
      - name: Test
        run: ./gradlew test
      - name: Publish
        run: ./gradlew artifactoryPublish -Djgitver.branch=${GITHUB_REF##*/} -PrepoUsername=${{ secrets.REPO_USR }} -PrepoPassword=${{ secrets.REPO_PSW }}
