name: Release

on:
  push: [tags]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Branch name
        run: echo running on branch ${GITHUB_REF}
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:10}"
      - name: Setup Java environment based on AdoptOpenJDK
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: openjdk11
          openjdk_impl: openj9
      - name: Init
        run: ./gradlew version
      - name: Compile
        run: ./gradlew classes
      - name: Test
        run: ./gradlew test
      - name: Publish
        run: ./gradlew artifactoryPublish -PrepoUsername=${{ secrets.REPO_USR }} -PrepoPassword=${{ secrets.REPO_PSW }}
